# See https://houndci.com/configuration for help.
eslint:
  config_file: .eslintrc
  enabled: true
javascript:
  enabled: false
ruby:
  enabled: true
scss:
  config_file: .scss-style.yml
  enabled: true
